FROM node:22-bookworm-slim
WORKDIR /app

COPY package*.json ./
RUN npm ci --include=optional

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ARG SUPABASE_KEY
ENV SUPABASE_KEY=$SUPABASE_KEY
ARG SUPABASE_SERVICE_KEY
ENV SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY

COPY . .
RUN rm -rf .next && npm run build \
	&& cp -r .next/static .next/standalone/.next/static \
	&& cp -r public .next/standalone/public

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["node", ".next/standalone/server.js"]
