/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  generateEtags: false,
  // Allow Jest (via nextJest) to transpile ESM-only packages in the react-markdown ecosystem
  transpilePackages: [
    'react-markdown',
    'unified',
    'bail',
    'is-plain-obj',
    'trough',
    'vfile',
    'vfile-message',
    'unist-util-stringify-position',
    'remark-parse',
    'remark-rehype',
    'mdast-util-from-markdown',
    'mdast-util-to-hast',
    'mdast-util-to-markdown',
    'mdast-util-to-string',
    'mdast-util-phrasing',
    'hast-util-to-jsx-runtime',
    'hast-util-whitespace',
    'hast-util-parse-selector',
    'hastscript',
    'html-url-attributes',
    'property-information',
    'space-separated-tokens',
    'comma-separated-tokens',
    'unist-util-visit',
    'unist-util-visit-parents',
    'unist-util-is',
    'unist-util-position',
    'devlop',
    'refractor',
    'micromark',
    'micromark-core-commonmark',
    'micromark-factory-destination',
    'micromark-factory-label',
    'micromark-factory-space',
    'micromark-factory-title',
    'micromark-factory-whitespace',
    'micromark-util-character',
    'micromark-util-chunked',
    'micromark-util-classify-character',
    'micromark-util-combine-extensions',
    'micromark-util-decode-numeric-character-reference',
    'micromark-util-decode-string',
    'micromark-util-encode',
    'micromark-util-html-tag-name',
    'micromark-util-normalize-identifier',
    'micromark-util-resolve-all',
    'micromark-util-sanitize-uri',
    'micromark-util-subtokenize',
    'micromark-util-symbol',
    'micromark-util-types',
    'decode-named-character-reference',
    'character-entities',
    'character-entities-html4',
    'character-entities-legacy',
    'character-reference-invalid',
    'trim-lines',
    'zwitch',
    'longest-streak',
    'stringify-entities',
    'parse-entities',
    'ccount',
    'is-alphabetical',
    'is-alphanumerical',
    'is-decimal',
    'is-hexadecimal',
    '@ungap/structured-clone',
    'estree-util-is-identifier-name',
    'mdast-util-mdx-expression',
    'mdast-util-mdx-jsx',
    'mdast-util-mdxjs-esm',
  ],
  headers: async () => [
    {
      source: '/(.*)',
      headers: [
        {
          key: 'Content-Security-Policy',
          value: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://assistantx.pl; style-src 'self' 'unsafe-inline'; img-src * blob: data:; font-src 'self'; connect-src *; frame-src 'self';"
        },
      ],
    },
    {
      source: '/_next/static/:path*',
      headers: [
        {
          key: 'Cache-Control',
          value: 'public, max-age=31536000, immutable',
        },
      ],
    },
  ],
};

export default nextConfig;
