import type { AssistantCommandDefinition, AssistantCommandId } from "./types";

export const ASSISTANT_COMMANDS: AssistantCommandDefinition[] = [
  {
    id: "os",
    slash: "/os",
    title: "System status",
    description: "Read CPU, memory, and local runtime status from your paired Jarvis device.",
    category: "system",
    executionMode: "local_only",
    riskLevel: "low",
    requiresDesktop: true,
    aliases: ["status", "system", "hardware", "cpu"],
    examples: ["/os", "system status", "status komputera"],
  },
  {
    id: "game",
    slash: "/game",
    title: "Launch game",
    description: "Launch a game on the paired Jarvis desktop.",
    category: "system",
    executionMode: "remote_on_paired_device",
    riskLevel: "medium",
    requiresDesktop: true,
    argsPlaceholder: "roblox",
    aliases: ["uruchom", "odpal", "graj"],
    examples: ["/game roblox", "uruchom roblox"],
  },
  {
    id: "open",
    slash: "/open",
    title: "Open app",
    description: "Open an application or desktop target on the paired Jarvis device.",
    category: "system",
    executionMode: "remote_on_paired_device",
    riskLevel: "medium",
    requiresDesktop: true,
    argsPlaceholder: "opera",
    aliases: ["open", "launch", "otwórz", "włącz"],
    examples: ["/open opera", "otwórz vscode"],
  },
  {
    id: "screenshot",
    slash: "/screenshot",
    title: "Take screenshot",
    description: "Capture a screenshot on the paired Jarvis device.",
    category: "system",
    executionMode: "remote_on_paired_device",
    riskLevel: "low",
    requiresDesktop: true,
    aliases: ["screen", "screen shot", "zrzut", "screenshot"],
    examples: ["/screenshot", "zrób zrzut ekranu"],
  },
  {
    id: "sleep",
    slash: "/sleep",
    title: "Sleep PC",
    description: "Put the paired Jarvis desktop to sleep.",
    category: "system",
    executionMode: "remote_on_paired_device",
    riskLevel: "high",
    requiresDesktop: true,
    aliases: ["sleep", "hibernate", "uśpij"],
    examples: ["/sleep", "uśpij komputer"],
  },
  {
    id: "repo",
    slash: "/repo",
    title: "Repo status",
    description: "Inspect the local repository workspace on the paired Jarvis device.",
    category: "repo",
    executionMode: "local_only",
    riskLevel: "low",
    requiresDesktop: true,
    argsPlaceholder: "path",
    aliases: ["repo", "repository"],
    examples: ["/repo", "/repo src"],
  },
  {
    id: "index",
    slash: "/index",
    title: "Index repo",
    description: "Refresh the local Jarvis file index for the paired workspace.",
    category: "repo",
    executionMode: "local_only",
    riskLevel: "medium",
    requiresDesktop: true,
    argsPlaceholder: "path",
    aliases: ["index", "scan repo", "indeksuj"],
    examples: ["/index", "/index src"],
  },
  {
    id: "file",
    slash: "/file",
    title: "Read file",
    description: "Read a local file from the paired Jarvis device.",
    category: "repo",
    executionMode: "remote_on_paired_device",
    riskLevel: "low",
    requiresDesktop: true,
    argsPlaceholder: "src/app.tsx",
    aliases: ["file", "read file", "plik"],
    examples: ["/file README.md", "read file package.json"],
  },
  {
    id: "search",
    slash: "/search",
    title: "Search workspace",
    description: "Search the local Jarvis workspace for files or matching text.",
    category: "repo",
    executionMode: "remote_on_paired_device",
    riskLevel: "low",
    requiresDesktop: true,
    argsPlaceholder: "auth callback",
    aliases: ["search", "find", "szukaj"],
    examples: ["/search auth callback", "szukaj parser"],
  },
  {
    id: "ignore",
    slash: "/ignore",
    title: "Update ignore rules",
    description: "Manage the Jarvis local ignore list for repo scans.",
    category: "repo",
    executionMode: "local_only",
    riskLevel: "medium",
    requiresDesktop: true,
    argsPlaceholder: "node_modules",
    aliases: ["ignore", "pomijaj"],
    examples: ["/ignore node_modules", "ignore .next"],
  },
  {
    id: "today",
    slash: "/today",
    title: "Today",
    description: "Show upcoming Google Calendar events for today and near-term agenda.",
    category: "google",
    executionMode: "cloud_direct",
    riskLevel: "low",
    requiresDesktop: false,
    aliases: ["plan", "dzisiaj", "agenda", "today"],
    examples: ["/today", "plan dnia"],
  },
  {
    id: "calendar",
    slash: "/calendar",
    title: "Calendar",
    description: "Create a Google Calendar event from the chat command.",
    category: "google",
    executionMode: "cloud_direct",
    riskLevel: "medium",
    requiresDesktop: false,
    argsPlaceholder: "Team sync tomorrow 10:00",
    aliases: ["calendar", "kalendarz", "spotkanie"],
    examples: ["/calendar Team sync tomorrow 10:00", "dodaj spotkanie jutro 10"],
  },
  {
    id: "gmail",
    slash: "/gmail",
    title: "Gmail",
    description: "Read or summarize recent Gmail inbox messages.",
    category: "google",
    executionMode: "cloud_direct",
    riskLevel: "low",
    requiresDesktop: false,
    argsPlaceholder: "important",
    aliases: ["gmail", "mail", "email", "poczta"],
    examples: ["/gmail invoices", "gmail ważne"],
  },
  {
    id: "draft",
    slash: "/draft",
    title: "Draft email",
    description: "Prepare an email draft workflow.",
    category: "google",
    executionMode: "cloud_direct",
    riskLevel: "medium",
    requiresDesktop: false,
    argsPlaceholder: "do clienta o demo",
    aliases: ["draft", "szkic", "napisz mail"],
    examples: ["/draft Demo follow-up to client", "napisz mail do klienta"],
  },
  {
    id: "drive",
    slash: "/drive",
    title: "Google Drive",
    description: "Import or inspect a Google Drive file.",
    category: "google",
    executionMode: "cloud_direct",
    riskLevel: "low",
    requiresDesktop: false,
    argsPlaceholder: "share link or file id",
    aliases: ["drive", "dysk", "google drive"],
    examples: ["/drive https://drive.google.com/...", "drive file id"],
  },
  {
    id: "web",
    slash: "/web",
    title: "Fetch webpage",
    description: "Fetch and summarize a webpage URL.",
    category: "web",
    executionMode: "cloud_direct",
    riskLevel: "low",
    requiresDesktop: false,
    argsPlaceholder: "https://example.com",
    aliases: ["web", "page", "website", "strona"],
    examples: ["/web https://example.com", "open page https://example.com"],
  },
  {
    id: "google",
    slash: "/google",
    title: "Web search",
    description: "Run a fresh web search.",
    category: "web",
    executionMode: "cloud_direct",
    riskLevel: "low",
    requiresDesktop: false,
    argsPlaceholder: "latest next.js 16 features",
    aliases: ["google", "search web", "wyszukaj", "szukaj w google"],
    examples: ["/google latest next.js 16 features", "wyszukaj news ai"],
  },
  {
    id: "slack",
    slash: "/slack",
    title: "Slack",
    description: "Read Slack channels or message history.",
    category: "web",
    executionMode: "cloud_direct",
    riskLevel: "medium",
    requiresDesktop: false,
    argsPlaceholder: "#general",
    aliases: ["slack"],
    examples: ["/slack #general", "slack release-updates"],
  },
  {
    id: "db",
    slash: "/db",
    title: "Database query",
    description: "Run a local database query on the paired Jarvis device.",
    category: "repo",
    executionMode: "local_only",
    riskLevel: "high",
    requiresDesktop: true,
    argsPlaceholder: "select * from users limit 5",
    aliases: ["db", "database", "postgres", "sql"],
    examples: ["/db select now()", "query postgres users"],
  },
  {
    id: "skills",
    slash: "/skills",
    title: "Skills",
    description: "Show cloud integrations and local PC/runtime capabilities in one merged view.",
    category: "jarvis",
    executionMode: "hybrid_dual",
    riskLevel: "low",
    requiresDesktop: false,
    aliases: ["skills", "capabilities", "tools"],
    examples: ["/skills", "show skills"],
  },
];

const COMMAND_MAP = new Map(ASSISTANT_COMMANDS.map((command) => [command.id, command] as const));

export function getAssistantCommand(id: AssistantCommandId) {
  return COMMAND_MAP.get(id) ?? null;
}

export function listAssistantCommands() {
  return ASSISTANT_COMMANDS;
}
