export const RUNTIME_EVENT_TYPES = {
  // Workflow lifecycle
  WORKFLOW_STARTED: "WORKFLOW_STARTED",
  WORKFLOW_COMPLETED: "WORKFLOW_COMPLETED",
  WORKFLOW_FAILED: "WORKFLOW_FAILED",
  WORKFLOW_CANCELLED: "WORKFLOW_CANCELLED",
  WORKFLOW_CHECKPOINT: "WORKFLOW_CHECKPOINT",
  START_GAMING_REQUESTED: "START_GAMING_REQUESTED",
  // Task lifecycle
  TASK_CREATED: "TASK_CREATED",
  TASK_COMPLETED: "TASK_COMPLETED",
  // Agent lifecycle
  AGENT_STARTED: "AGENT_STARTED",
  AGENT_FAILED: "AGENT_FAILED",
  // Tool execution
  TOOL_EXECUTED: "TOOL_EXECUTED",
  TOOL_RATE_LIMITED: "TOOL_RATE_LIMITED",
  TOOL_APPROVAL_REQUIRED: "TOOL_APPROVAL_REQUIRED",
  // Policy
  POLICY_DENIED: "POLICY_DENIED",
  // Memory
  MEMORY_UPDATED: "MEMORY_UPDATED",
  // Approvals
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_RESOLVED: "APPROVAL_RESOLVED",
  // Cost
  COST_RECORDED: "COST_RECORDED",
  // MCP
  MCP_TOOL_CALLED: "MCP_TOOL_CALLED",
  // Plugins
  PLUGIN_INSTALLED: "PLUGIN_INSTALLED",
  PLUGIN_REMOVED: "PLUGIN_REMOVED",
  // Org / audit
  ORG_ACTION: "ORG_ACTION",
  AUDIT_LOG: "AUDIT_LOG",
} as const;

export type RuntimeEventType = (typeof RUNTIME_EVENT_TYPES)[keyof typeof RUNTIME_EVENT_TYPES];

export type RuntimeEvent = {
  type: RuntimeEventType;
  timestamp: string;
  actorUserId?: string | null;
  organizationId?: string | null;
  executionId?: string;
  payload: Record<string, unknown>;
};
