"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { createClient } from "@/lib/client";
import { getDeviceType } from "@/lib/device-detection";
import {
  normalizePairingCode,
  type PairingStatus,
  type PairingStatusResponse,
} from "@/lib/device-pairing";

type UseDevicePairingState = PairingStatusResponse & {
  status: PairingStatus;
};

const DEFAULT_STATE: UseDevicePairingState = { status: "none" };

function applyState(setState: Dispatch<SetStateAction<UseDevicePairingState>>, nextState: PairingStatusResponse) {
  setState({
    status: nextState.status,
    code: nextState.code ?? null,
    expiresAt: nextState.expiresAt ?? null,
    pairedAt: nextState.pairedAt ?? null,
    initiatorDevice: nextState.initiatorDevice ?? null,
  });
}

export function useDevicePairing() {
  const [pairingState, setPairingState] = useState<UseDevicePairingState>(DEFAULT_STATE);
  const [ready, setReady] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [isConfirming, setIsConfirming] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const deviceType = useMemo(() => getDeviceType(), []);
  const autoGenerateInFlightRef = useRef(false);
  const autoGeneratedForCurrentNoneRef = useRef(false);

  const fetchStatus = useCallback(async () => {
    const response = await fetch("/api/pairing/status", { cache: "no-store" });
    const payload = await response.json().catch(() => ({})) as PairingStatusResponse & { error?: string };

    if (!response.ok) {
      if (response.status === 401) {
        applyState(setPairingState, { status: "none" });
        setErrorMessage(null);
        return { status: "none" } satisfies PairingStatusResponse;
      }
      throw new Error(payload.error ?? "Failed to load device pairing status.");
    }

    applyState(setPairingState, payload);
    setErrorMessage(null);
    return payload;
  }, []);

  const refreshPairingCode = useCallback(async () => {
    setIsRefreshing(true);
    try {
      const response = await fetch("/api/pairing/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ initiatorDevice: deviceType }),
      });
      const payload = await response.json().catch(() => ({})) as PairingStatusResponse & { error?: string; code?: string };

      if (!response.ok) {
        throw new Error(payload.error ?? "Failed to generate a pairing code.");
      }

      applyState(setPairingState, {
        status: "pending",
        code: payload.code ?? null,
        expiresAt: payload.expiresAt ?? null,
        pairedAt: null,
        initiatorDevice: deviceType,
      });
      setErrorMessage(null);
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : "Failed to generate a pairing code.");
    } finally {
      setIsRefreshing(false);
    }
  }, [deviceType]);

  const confirmPairing = useCallback(async (code: string) => {
    setIsConfirming(true);
    try {
      const response = await fetch("/api/pairing/confirm", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code: normalizePairingCode(code) }),
      });
      const payload = await response.json().catch(() => ({})) as { error?: string };

      if (!response.ok) {
        throw new Error(payload.error ?? "Failed to confirm device pairing.");
      }

      await fetchStatus();
      setErrorMessage(null);
      return { ok: true as const };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to confirm device pairing.";
      setErrorMessage(message);
      return { ok: false as const, error: message };
    } finally {
      setIsConfirming(false);
    }
  }, [fetchStatus]);

  const clearPairingError = useCallback(() => {
    setErrorMessage(null);
  }, []);

  useEffect(() => {
    if (pairingState.status !== "none") {
      autoGeneratedForCurrentNoneRef.current = false;
    }
  }, [pairingState.status]);

  useEffect(() => {
    if (typeof window === "undefined") return;

    let active = true;
    const timeoutId = window.setTimeout(() => {
      void fetchStatus()
        .then((status) => {
          if (!active) return;
          setReady(true);
          if (
            deviceType === "phone"
            && status.status === "none"
            && !autoGenerateInFlightRef.current
            && !autoGeneratedForCurrentNoneRef.current
          ) {
            autoGeneratedForCurrentNoneRef.current = true;
            autoGenerateInFlightRef.current = true;
            void refreshPairingCode().finally(() => {
              autoGenerateInFlightRef.current = false;
            });
          }
        })
        .catch((error) => {
          if (!active) return;
          setReady(true);
          setErrorMessage(error instanceof Error ? error.message : "Failed to load device pairing status.");
        });
    }, 0);

    return () => {
      active = false;
      window.clearTimeout(timeoutId);
    };
  }, [deviceType, fetchStatus, refreshPairingCode]);

  useEffect(() => {
    if (
      !ready
      || deviceType !== "phone"
      || pairingState.status !== "none"
      || isRefreshing
      || autoGenerateInFlightRef.current
      || autoGeneratedForCurrentNoneRef.current
    ) {
      return;
    }

    autoGeneratedForCurrentNoneRef.current = true;
    autoGenerateInFlightRef.current = true;
    void refreshPairingCode().finally(() => {
      autoGenerateInFlightRef.current = false;
    });
  }, [deviceType, isRefreshing, pairingState.status, ready, refreshPairingCode]);

  useEffect(() => {
    if (pairingState.status !== "pending") return;
    const intervalId = window.setInterval(() => {
      void fetchStatus().catch(() => null);
    }, 5000);
    return () => {
      window.clearInterval(intervalId);
    };
  }, [fetchStatus, pairingState.status]);

  useEffect(() => {
    if (typeof window === "undefined") return;

    const supabase = createClient();
    let active = true;
    let channel: ReturnType<ReturnType<typeof createClient>["channel"]> | null = null;

    void supabase.auth.getSession().then(({ data: { session } }) => {
      if (!active || !session?.user?.id) return;

      channel = supabase
        .channel(`device-pairs:${session.user.id}`)
        .on(
          "postgres_changes",
          {
            event: "*",
            schema: "public",
            table: "device_pairs",
            filter: `user_id=eq.${session.user.id}`,
          },
          () => {
            if (!active) return;
            void fetchStatus().catch(() => null);
          }
        )
        .subscribe();
    }).catch(() => null);

    return () => {
      active = false;
      if (channel) {
        void channel.unsubscribe();
      }
    };
  }, [fetchStatus]);

  return {
    deviceType,
    ready,
    pairingStatus: pairingState.status,
    pairingCode: pairingState.code ?? null,
    expiresAt: pairingState.expiresAt ?? null,
    pairedAt: pairingState.pairedAt ?? null,
    initiatorDevice: pairingState.initiatorDevice ?? null,
    isRefreshing,
    isConfirming,
    errorMessage,
    fetchStatus,
    refreshPairingCode,
    confirmPairing,
    clearPairingError,
  };
}
